### ISSUE TITLE
Problem when creating and launching a Nessus scan

### ISSUE THREAD

**Issue by mobashua** [leonjza/PHPNessusNG#14]
Hello,

When I create and launch a scan by using : 
![nessus_launch_scan](https://cloud.githubusercontent.com/assets/3640812/9351277/443ca6f8-4658-11e5-9c42-784db496c00b.PNG)

I can't get it to process the targets I just gave it, even though in the GUI, I can see the targets set up.
The scan give no result, not being able to process the targets

Thank you

**Comment by leonjza** [comment]
Hey, which Nessus version are you testing against?

**Comment by mobashua** [comment]
API v6 
Nessus  6.4.1

**Comment by leonjza** [comment]
Just to confirm, in the Nessus HTML5 UI, you can see the targets that you have specified via the API, but the scan itself has no results? Could it be that the IP is not live / fire-walled out?

Are there any specific error messages that  come about anywhere?

**Comment by mobashua** [comment]
Exactly, I can see in the GUI the targets previously specified but the scan has no results. 
The IP is live, there's no problem about that.

A really weird thing, though : 
After launching the scan which will give me no results, I configure the targets by adding some comma, some space, or by entering 'enter' in the area. 
Without modifying the targets itselves, I launch again the scan and it gives me the results I would expect.

No messages indicating an error is displayed.

**Comment by mobashua** [comment]
I configure the targets by adding some comma, some space, or by entering 'enter' in the *GUI textarea

**Comment by leonjza** [comment]
Ok thanks. Ill setup some local testing to see if I can replicate this. Could you try by adding say a trailing comma to the API code and see if that makes any difference?

Thanks.

**Comment by mobashua** [comment]
No difference at all.

**Comment by mobashua** [comment]
Hello, 

I succeeded in launching a successful scan by adding this line in my code : 
![nessus_launch_scan](https://cloud.githubusercontent.com/assets/3640812/9388114/f1d71a12-4763-11e5-9746-673a4e0cbe0e.PNG)

By doing that, I tell it to take into account the policy I created.

Thank you.

**Comment by leonjza** [comment]
Thank you for the feedback!
