### ISSUE TITLE
Download .nessus incomplete

### ISSUE THREAD

**Issue by zionl** [leonjza/PHPNessusNG#20]
Hi, 

First: Thank you for making so amazing work! 

I am having problems downloading .nessus, for that I am using the same .php that you have here: https://github.com/leonjza/PHPNessusNG/blob/master/examples/scans.php

That code is downloading partially the scan, sometimes it downloads only 2 of 8 MB and only in 3 times it has been able to download the complete .nessus.

Please, help me, I haven't made any modification to the script. 

Kind regards and thanks in advance!

**Comment by leonjza** [comment]
Hey. Off the top of my head I cant really say what is causing the incomplete downloads, but I would first check that the network connection between the place you are running your script and the nessus scanner is stable. Could you verify that?

**Comment by zionl** [comment]
Thank you for taking of your time to answer me!

I was doing it thru a VPN, it looks that that's what's the problem because when I run it from localhost it works perfectly. Thank you very much for your work!

Best regards!
